In [1]:
import pandas as pd
import json

In [31]:
with open ('t20_wc_match_results.json') as f:
    data= json.load(f)

dt_match = pd.DataFrame(data[0]['matchSummary'])
dt_match.head()

,team1,team2,winner,margin,ground,matchDate,scorecard
0,Namibia,Sri Lanka,Namibia,55 runs,Geelong,"Oct 16, 2022",T20I # 1823
1,Netherlands,U.A.E.,Netherlands,3 wickets,Geelong,"Oct 16, 2022",T20I # 1825
2,Scotland,West Indies,Scotland,42 runs,Hobart,"Oct 17, 2022",T20I # 1826
3,Ireland,Zimbabwe,Zimbabwe,31 runs,Hobart,"Oct 17, 2022",T20I # 1828
4,Namibia,Netherlands,Netherlands,5 wickets,Geelong,"Oct 18, 2022",T20I # 1830

In [54]:
dt_match.rename({'scorecard':'match_id'},axis=1,inplace=1)
dt_match.head()

,team1,team2,winner,margin,ground,matchDate,match_id
0,Namibia,Sri Lanka,Namibia,55 runs,Geelong,"Oct 16, 2022",T20I # 1823
1,Netherlands,U.A.E.,Netherlands,3 wickets,Geelong,"Oct 16, 2022",T20I # 1825
2,Scotland,West Indies,Scotland,42 runs,Hobart,"Oct 17, 2022",T20I # 1826
3,Ireland,Zimbabwe,Zimbabwe,31 runs,Hobart,"Oct 17, 2022",T20I # 1828
4,Namibia,Netherlands,Netherlands,5 wickets,Geelong,"Oct 18, 2022",T20I # 1830

In [65]:
match_ids_dict = {}
for index,row in dt_match.iterrows():
    key1 = row['team1']+ ' Vs ' +row['team2']
    key2 = row['team2']+ ' Vs ' +row['team1']
    
    match_ids_dict[key1]=row['match_id']
    match_ids_dict[key2]=row['match_id']

In [ ]:
# **batting summary**

In [46]:
with open('t20_wc_batting_summary.json') as f:
    data= json.load(f)
    all_record=[]
    for rec in data:
        all_record.extend(rec['battingSummary'])
        
df_batting = pd.DataFrame(all_record)
df_batting.head(30)

,match,teamInnings,battingPos,batsmanName,dismissal,runs,balls,4s,6s,SR
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,c Pramod Madushan b Chameera,3,6,0,0,50.00
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,c Shanaka b Pramod Madushan,9,9,1,0,100.00
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,c †Mendis b Karunaratne,20,12,1,2,166.66
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,c DM de Silva b Pramod Madushan,26,24,2,0,108.33
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus(c),c Gunathilaka b PWH de Silva,20,24,0,0,83.33
5,Namibia Vs Sri Lanka,Namibia,6,Jan Frylinck,run out (Gunathilaka/†Mendis),44,28,4,0,157.14
6,Namibia Vs Sri Lanka,Namibia,7,David Wiese,c †Mendis b Theekshana,0,1,0,0,0.00
7,Namibia Vs Sri Lanka,Namibia,8,JJ Smit,,31,16,2,2,193.75
8,Namibia Vs Sri Lanka,Sri Lanka,1,Pathum Nissanka,c Smit b Shikongo,9,10,1,0,90.00
9,Namibia Vs Sri Lanka,Sri Lanka,2,Kusal Mendis†,c †Green b Wiese,6,6,0,0,100.00
10,Namibia Vs Sri Lanka,Sri Lanka,3,Dhananjaya de Silva,c Shikongo b Frylinck,12,11,1,0,109.09
11,Namibia Vs Sri Lanka,Sri Lanka,4,Danushka Gunathilaka,c †Green b Shikongo,0,1,0,0,0.00
12,Namibia Vs Sri Lanka,Sri Lanka,5,Bhanuka Rajapaksa,c la Cock b Scholtz,20,21,2,0,95.23
13,Namibia Vs Sri Lanka,Sri Lanka,6,Dasun Shanaka(c),c †Green b Frylinck,29,23,2,1,126.08
14,Namibia Vs Sri Lanka,Sri Lanka,7,Wanindu Hasaranga de Silva,c Loftie-Eaton b Scholtz,4,8,0,0,50.00
15,Namibia Vs Sri Lanka,Sri Lanka,8,Chamika Karunaratne,c Baard b Smit,5,8,0,0,62.50
16,Namibia Vs Sri Lanka,Sri Lanka,9,Pramod Madushan,run out (van Lingen/†Green),0,0,0,0,-
17,Namibia Vs Sri Lanka,Sri Lanka,10,Dushmantha Chameera,c Erasmus b Wiese,8,15,0,0,53.33
18,Namibia Vs Sri Lanka,Sri Lanka,11,Maheesh Theekshana,,11,11,0,1,100.00
19,U.A.E. Vs Netherlands,U.A.E.,1,Chirag Suri,c †Edwards b van der Merwe,12,20,1,0,60.00
20,U.A.E. Vs Netherlands,U.A.E.,2,Muhammad Waseem,c Pringle b Klaassen,41,47,1,2,87.23
21,U.A.E. Vs Netherlands,U.A.E.,3,Kashif Daud,b Pringle,15,14,0,1,107.14
22,U.A.E. Vs Netherlands,U.A.E.,4,Vriitya Aravind†,c Klaassen b de Leede,18,21,0,0,85.71
23,U.A.E. Vs Netherlands,U.A.E.,5,Zawar Farid,run out (Ackermann/†Edwards),2,4,0,0,50.00
24,U.A.E. Vs Netherlands,U.A.E.,6,Basil Hameed,c van der Merwe b de Leede,4,4,1,0,100.00
25,U.A.E. Vs Netherlands,U.A.E.,7,Chundangapoyil Rizwan(c),b de Leede,1,2,0,0,50.00
26,U.A.E. Vs Netherlands,U.A.E.,8,Aayan Afzal Khan,c Cooper b Klaassen,5,7,0,0,71.42
27,U.A.E. Vs Netherlands,U.A.E.,9,Karthik Meiyappan,,0,0,0,0,-
28,U.A.E. Vs Netherlands,U.A.E.,10,Junaid Siddique,,0,1,0,0,0.00
29,U.A.E. Vs Netherlands,Netherlands,1,Vikramjit Singh,b Basil Hameed,10,7,2,0,142.85

In [43]:
df_batting["out/not_out"]= df_batting.dismissal.apply(lambda x: "out" if len(x)>0 else "not_out")
df_batting.head(12)

,match,teamInnings,battingPos,batsmanName,dismissal,runs,balls,4s,6s,SR,out/not_out
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,c Pramod Madushan b Chameera,3,6,0,0,50.00,out
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,c Shanaka b Pramod Madushan,9,9,1,0,100.00,out
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,c †Mendis b Karunaratne,20,12,1,2,166.66,out
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,c DM de Silva b Pramod Madushan,26,24,2,0,108.33,out
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus(c),c Gunathilaka b PWH de Silva,20,24,0,0,83.33,out
5,Namibia Vs Sri Lanka,Namibia,6,Jan Frylinck,run out (Gunathilaka/†Mendis),44,28,4,0,157.14,out
6,Namibia Vs Sri Lanka,Namibia,7,David Wiese,c †Mendis b Theekshana,0,1,0,0,0.00,out
7,Namibia Vs Sri Lanka,Namibia,8,JJ Smit,,31,16,2,2,193.75,not_out
8,Namibia Vs Sri Lanka,Sri Lanka,1,Pathum Nissanka,c Smit b Shikongo,9,10,1,0,90.00,out
9,Namibia Vs Sri Lanka,Sri Lanka,2,Kusal Mendis†,c †Green b Wiese,6,6,0,0,100.00,out
10,Namibia Vs Sri Lanka,Sri Lanka,3,Dhananjaya de Silva,c Shikongo b Frylinck,12,11,1,0,109.09,out
11,Namibia Vs Sri Lanka,Sri Lanka,4,Danushka Gunathilaka,c †Green b Shikongo,0,1,0,0,0.00,out

In [44]:
df_batting.drop(columns=["dismissal"],inplace=True)
df_batting.tail()

,match,teamInnings,battingPos,batsmanName,runs,balls,4s,6s,SR,out/not_out
694,Pakistan Vs England,England,3,Phil Salt,10,9,2,0,111.11,out
695,Pakistan Vs England,England,4,Ben Stokes,52,49,5,1,106.12,not_out
696,Pakistan Vs England,England,5,Harry Brook,20,23,1,0,86.95,out
697,Pakistan Vs England,England,6,Moeen Ali,19,13,3,0,146.15,out
698,Pakistan Vs England,England,7,Liam Livingstone,1,1,0,0,100.00,not_out

In [49]:
df_batting['batsmanName']=df_batting['batsmanName'].apply(lambda x: x.replace('\xa0',''))
df_batting['batsmanName']=df_batting['batsmanName'].apply(lambda x: x.replace('†',''))
df_batting.head(30)

,match,teamInnings,battingPos,batsmanName,dismissal,runs,balls,4s,6s,SR
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,c Pramod Madushan b Chameera,3,6,0,0,50.00
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,c Shanaka b Pramod Madushan,9,9,1,0,100.00
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,c †Mendis b Karunaratne,20,12,1,2,166.66
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,c DM de Silva b Pramod Madushan,26,24,2,0,108.33
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus(c),c Gunathilaka b PWH de Silva,20,24,0,0,83.33
5,Namibia Vs Sri Lanka,Namibia,6,Jan Frylinck,run out (Gunathilaka/†Mendis),44,28,4,0,157.14
6,Namibia Vs Sri Lanka,Namibia,7,David Wiese,c †Mendis b Theekshana,0,1,0,0,0.00
7,Namibia Vs Sri Lanka,Namibia,8,JJ Smit,,31,16,2,2,193.75
8,Namibia Vs Sri Lanka,Sri Lanka,1,Pathum Nissanka,c Smit b Shikongo,9,10,1,0,90.00
9,Namibia Vs Sri Lanka,Sri Lanka,2,Kusal Mendis,c †Green b Wiese,6,6,0,0,100.00
10,Namibia Vs Sri Lanka,Sri Lanka,3,Dhananjaya de Silva,c Shikongo b Frylinck,12,11,1,0,109.09
11,Namibia Vs Sri Lanka,Sri Lanka,4,Danushka Gunathilaka,c †Green b Shikongo,0,1,0,0,0.00
12,Namibia Vs Sri Lanka,Sri Lanka,5,Bhanuka Rajapaksa,c la Cock b Scholtz,20,21,2,0,95.23
13,Namibia Vs Sri Lanka,Sri Lanka,6,Dasun Shanaka(c),c †Green b Frylinck,29,23,2,1,126.08
14,Namibia Vs Sri Lanka,Sri Lanka,7,Wanindu Hasaranga de Silva,c Loftie-Eaton b Scholtz,4,8,0,0,50.00
15,Namibia Vs Sri Lanka,Sri Lanka,8,Chamika Karunaratne,c Baard b Smit,5,8,0,0,62.50
16,Namibia Vs Sri Lanka,Sri Lanka,9,Pramod Madushan,run out (van Lingen/†Green),0,0,0,0,-
17,Namibia Vs Sri Lanka,Sri Lanka,10,Dushmantha Chameera,c Erasmus b Wiese,8,15,0,0,53.33
18,Namibia Vs Sri Lanka,Sri Lanka,11,Maheesh Theekshana,,11,11,0,1,100.00
19,U.A.E. Vs Netherlands,U.A.E.,1,Chirag Suri,c †Edwards b van der Merwe,12,20,1,0,60.00
20,U.A.E. Vs Netherlands,U.A.E.,2,Muhammad Waseem,c Pringle b Klaassen,41,47,1,2,87.23
21,U.A.E. Vs Netherlands,U.A.E.,3,Kashif Daud,b Pringle,15,14,0,1,107.14
22,U.A.E. Vs Netherlands,U.A.E.,4,Vriitya Aravind,c Klaassen b de Leede,18,21,0,0,85.71
23,U.A.E. Vs Netherlands,U.A.E.,5,Zawar Farid,run out (Ackermann/†Edwards),2,4,0,0,50.00
24,U.A.E. Vs Netherlands,U.A.E.,6,Basil Hameed,c van der Merwe b de Leede,4,4,1,0,100.00
25,U.A.E. Vs Netherlands,U.A.E.,7,Chundangapoyil Rizwan(c),b de Leede,1,2,0,0,50.00
26,U.A.E. Vs Netherlands,U.A.E.,8,Aayan Afzal Khan,c Cooper b Klaassen,5,7,0,0,71.42
27,U.A.E. Vs Netherlands,U.A.E.,9,Karthik Meiyappan,,0,0,0,0,-
28,U.A.E. Vs Netherlands,U.A.E.,10,Junaid Siddique,,0,1,0,0,0.00
29,U.A.E. Vs Netherlands,Netherlands,1,Vikramjit Singh,b Basil Hameed,10,7,2,0,142.85

In [66]:
df_batting["match_id"]=df_batting["match"].map(match_ids_dict)
df_batting.head()

,match,teamInnings,battingPos,batsmanName,dismissal,runs,balls,4s,6s,SR,match_id
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,c Pramod Madushan b Chameera,3,6,0,0,50.00,T20I # 1823
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,c Shanaka b Pramod Madushan,9,9,1,0,100.00,T20I # 1823
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,c †Mendis b Karunaratne,20,12,1,2,166.66,T20I # 1823
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,c DM de Silva b Pramod Madushan,26,24,2,0,108.33,T20I # 1823
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus(c),c Gunathilaka b PWH de Silva,20,24,0,0,83.33,T20I # 1823